name: dairv2x_sdcoper_intermediate_fusion
yaml_parser: "load_point_pillar_params"

noise_setting:
  add_noise: True
  args:
    pos_std: 0.2
    rot_std: 0.2
    pos_mean: 0
    rot_mean: 0

data_dir: "/datasets/DAIR-V2X/cooperative-vehicle-infrastructure"
root_dir: "/datasets/DAIR-V2X/cooperative-vehicle-infrastructure/train.json"
validate_dir: "/datasets/DAIR-V2X/cooperative-vehicle-infrastructure/val.json"
test_dir: "/datasets/DAIR-V2X/cooperative-vehicle-infrastructure/val.json"

input_source: ['lidar']
label_type: 'lidar'

comm_range: 100

train_params:
  batch_size: &batch_size 2

  epoches: 89
  eval_freq: 2
  save_freq: 1
  max_cav: &max_cav 5

fusion:
  core_method: 'decdiffusiondair' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset supported
  dataset: 'dairv2x'
  args:
    proj_first: &proj_first false

# preprocess-related
preprocess: &preprocess
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: 'SpVoxelPreprocessor'
  args:
    voxel_size: &voxel_size [0.4, 0.4, 5]
    max_points_per_voxel: &T 32
    voxel_size_car: &voxel_size_car [0.1, 0.1, 5.0]
    max_points_per_voxel_car: &T_car 16
    max_voxel_train: 32000
    max_voxel_test: 70000
    max_hwl: &max_hwl [1.98,2.36,5.63] #[1.98,2.36,5.63]
    use_hwl: true
  # lidar range for each individual cav.
  cav_lidar_range: &cav_lidar [-100.8, -40, -3.5, 100.8, 40, 1.5]
  keep_original_lidar: true

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# anchor box related
postprocess: &postprocess_params
  core_method: 'FpvrcnnPostprocessor' # VoxelPostprocessor, BevPostprocessor, FpvrcnnPostprocessor supported
  gt_range: *cav_lidar
  iou_stage1: False
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 4.5
    w: 2
    h: 1.56
    r: &anchor_yaw [0, 90]
    feature_stride: 2
    num: &achor_num 2
  target_args:
    # pos_threshold: 0.6
    pos_threshold: 0.75
    neg_threshold: 0.45
    score_threshold: 0.20
  order: 'hwl' # hwl or lwh
  max_num: 100 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15
  dir_args: &dir_args
    dir_offset: 0.7853
    num_bins: 2
    anchor_yaw: *anchor_yaw

# model related
model:
  core_method: point_pillar_diffusion_dec_det_dair #fpvrcnn_cobevt_compare
  args:
#    activate_stage2: False
    activate_stage2: True
    is_inference: false
    # is_inference: true
    N: *batch_size
    T: *T
    lidar_range: *cav_lidar
    voxel_size: *voxel_size
    anchor_num: *achor_num
    anchor_number: *achor_num
    max_cav: *max_cav
    max_hwl: *max_hwl 
    # compression: 0 # compression rate
    backbone_fix: false
    supervise_single: false

    preprocess: *preprocess
    post_processer: *postprocess_params

    mean_vfe:
      num_point_features: 4
    spconv:
      num_features_in: 4
      num_features_out: 64
    map2bev:
      feature_num: 128
    ssfa:
      feature_num: 128
    head:
#      num_input: 128
      num_input: 256
      num_pred: 14
      num_cls: 2
      num_iou: 2
      use_dir: True
      num_dir: 4
    
    vsa:
      enlarge_selection_boxes: true
      point_source: 'raw_points'
      num_keypoints: 4096

      num_out_features: &cpm_features 32

      features_source:
        dec_spatial_features: 64
        dec_spatial_features_2x: 64
        dec_spatial_features_4x: 128
        dec_spatial_features_8x: 256


      features_stride:
        dec_spatial_features: 1
        dec_spatial_features_2x: 2
        dec_spatial_features_4x: 4
        dec_spatial_features_8x: 8

      sa_layer:
        raw_points:
          mlps: [[16, 16], [16, 16]]
          pool_radius: [0.4, 0.8]
          n_sample: [16, 16]
        x_conv1:
          downsample_factor: 1
          mlps: [[16, 16], [16, 16]]
          pool_radius: [0.4, 0.8]
          n_sample: [16, 16]
        x_conv2:
          downsample_factor: 2
          mlps: [[32, 32], [32, 32]]
          pool_radius: [0.8, 1.2]
          n_sample: [16, 32]
        x_conv3:
          downsample_factor: 4
          mlps: [[64, 64], [64, 64]]
          pool_radius: [1.2, 2.4]
          n_sample: [16, 32]
        x_conv4:
          downsample_factor: 8
          mlps: [[64, 64], [64, 64]]
          pool_radius: [2.4, 4.8]
          n_sample: [16, 32]
    matcher: 'none' # may need to configure parameters for loc correction
    roi_head:
      num_cls: 1
      in_channels: *cpm_features
      n_fc_neurons: 256
      dp_ratio: 0.3 # dropout ratio
      roi_grid_pool:
        grid_size: 6
        mlps: [[64, 64], [64, 64]]
        pool_radius: [0.8, 1.6]
        n_sample: [16, 16]
        pool_method: 'max_pool'
    
    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [64]
    point_pillar_scatter:
      max_hwl: *max_hwl
      num_features: &num_features 4 # pillar_features维度
      num_features_dec: &num_features_dec 64 
      voxel_size: *voxel_size
      lidar_range: *cav_lidar
    
    base_bev_backbone: # backbone will downsample 2x
      layer_nums: [ 3, 5, 8 ]
      layer_strides: [ 2, 2, 2 ]
      num_filters: [ 64, 128, 256 ]
      upsample_strides: [ 1, 2, 4 ]
      num_upsample_filter: [ 128, 128, 128 ]

    fusion_method: att
    att:
      feat_dim: [ 64, 128, 256 ]

    shrink_header:
      kernal_size: [ 3 ]
      stride: [ 1 ]
      padding: [ 1 ]
      dim: [ 256 ]
      input_dim: 384 # 128 * 3

    dir_args: *dir_args

    mdd_block:
      model:
        in_channels: 1 #*num_features 1
        out_ch: 1 #*num_features 1
        ch: 64 #64 16
        flash_attn: False #True
        ch_mult: [1, 2, 4] #[1, 2, 4, 8] [1, 1]
        num_res_blocks: 2
        attn_resolutions: 12 #16
        resolution: 24
        dropout: 0.0
        resamp_with_conv: True
        d_cond: 256 #256 512
        n_head: 4 #8
      diffusion:
        beta_schedule: linear
        num_diffusion_timesteps: 1000
        sampling_timesteps: 1000
        # if_normalize: False
        if_normalize: True
        ddim_sampling_eta: 0.0
        guidance_scale: 7.5
        parameterization: 'eps'
        # parameterization: 'x0'
    
    anchor_num: *achor_num

    dete_hidden: 512

loss:
  core_method: fpvrcnn_loss_diffusion
  args:
    stage1:
      pos_cls_weight: 2.0
      encode_rad_error_by_sin: true
      cls:
        type: 'SigmoidFocalLoss'
        alpha: 0.25
        gamma: 2.0
        weight: 2.0
      reg:
        type: 'WeightedSmoothL1Loss'
        sigma: 3.0
        codewise: true
        weight: 2.0
      dir:
        type: 'WeightedSoftmaxClassificationLoss'
        weight: 0.2
        args: *dir_args
      iou: &iou
        type: 'WeightedSmoothL1Loss'
        sigma: 3.0
        codewise: true
        weight: 1.0

      use_iou: False

    stage2:
      cls:
        type: 'WeightedSigmoidBinaryCELoss'
        weight: 1.0
      iou: *iou
      reg:
        type: 'WeightedSmoothL1Loss'
        sigma: 3.0
        reduction: 'mean'
        code_weights: [20.0]
        weight: 1.0

optimizer:
  core_method: AdamW
  lr: 1e-4
  args:
    eps: 1e-10
    weight_decay: 1e-4

# lr_scheduler:
#   core_method: multistep #step, multistep and Exponential support
#   gamma: 0.1
#   step_size: [10, 20]

# lr_scheduler:
#   core_method: exponential
#   gamma: 0.8  # 或0.85-0.9之间的值
lr_scheduler:
  core_method: 'cosine_warmup'
  num_warmup_steps: 100










# box_align:
#   train_result: "opencood/logs/coalign_precalc/opv2v/train/stage1_boxes.json"
#   val_result: "opencood/logs/coalign_precalc/opv2v/val/stage1_boxes.json"
#   test_result: "opencood/logs/coalign_precalc/opv2v/test/stage1_boxes.json"
#   args:
#     use_uncertainty: true
#     landmark_SE2: true
#     adaptive_landmark: false
#     normalize_uncertainty: false
#     abandon_hard_cases: true
#     drop_hard_boxes: true




#loss:
#  core_method: point_pillar_loss
#  args:
#    pos_cls_weight: 2.0
#    cls:
#      type: 'SigmoidFocalLoss'
#      alpha: 0.25
#      gamma: 2.0
#      weight: 2.0
#    reg:
#      type: 'WeightedSmoothL1Loss'
#      sigma: 3.0
#      codewise: true
#      weight: 2.0
#    dir:
#      type: 'WeightedSoftmaxClassificationLoss'
#      weight: 0.2
#      args: *dir_args




